name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Run the Windows Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
        with:
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v6
        with:
          name: Build
          path: build
